name: video_duration_native
description: Lightweight native duration reader (Android/iOS) by path or content URI. No FFmpeg, no byte loading.
version: 0.2.0+2
homepage: https://github.com/Ddarkbooked/video_duration_native
repository: https://github.com/Ddarkbooked/video_duration_native
issue_tracker: https://github.com/Ddarkbooked/video_duration_native/issues

environment:
  sdk: ^3.9.0

flutter:
  plugin:
    platforms:
      android:
        default_package: video_duration_native_android
      ios:
        default_package: video_duration_native_ios

dependencies:
  flutter:
    sdk: flutter
  video_duration_native_android: ^0.2.0+2
  video_duration_native_ios: ^0.2.0+2
  video_duration_native_platform_interface: ^0.2.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^10.0.0
