name: video_duration_native_android
description: Android implementation of the video_duration_native plugin
version: 0.2.0+2
homepage: https://github.com/Ddarkbooked/video_duration_native
repository: https://github.com/Ddarkbooked/video_duration_native
issue_tracker: https://github.com/Ddarkbooked/video_duration_native/issues

environment:
  sdk: ^3.9.0
  flutter: ">=1.20.0"

flutter:
  plugin:
    implements: video_duration_native
    platforms:
      android:
        package: com.github.ddarkbooked.video_duration_native
        pluginClass: VideoDurationNativePlugin
        dartPluginClass: VideoDurationNativeAndroid

dependencies:
  flutter:
    sdk: flutter
  video_duration_native_platform_interface: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^10.0.0
