name: video_duration_native_platform_interface
description: A common platform interface for the video_duration_native plugin.
version: 0.1.0+1
homepage: https://github.com/Ddarkbooked/video_duration_native
repository: https://github.com/Ddarkbooked/video_duration_native
issue_tracker: https://github.com/Ddarkbooked/video_duration_native/issues

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0
