name: video_duration_native_ios
description: iOS implementation of the video_duration_native plugin
version: 0.2.1+4
homepage: https://github.com/Ddarkbooked/video_duration_native
repository: https://github.com/Ddarkbooked/video_duration_native
issue_tracker: https://github.com/Ddarkbooked/video_duration_native/issues

environment:
  sdk: ^3.9.0
  flutter: ">=1.20.0"

flutter:
  plugin:
    implements: video_duration_native
    platforms:
      ios:
        pluginClass: VideoDurationNativePlugin
        dartPluginClass: VideoDurationNativeIOS

dependencies:
  flutter:
    sdk: flutter
  video_duration_native_platform_interface: ^0.2.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^10.0.0
