name: video_duration_native_ios
description: iOS implementation of the video_duration_native plugin
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.9.0

flutter:
  plugin:
    implements: video_duration_native
    platforms:
      ios:
        pluginClass: VideoDurationNativePlugin
        dartPluginClass: VideoDurationNativeIOS

dependencies:
  flutter:
    sdk: flutter
  video_duration_native_platform_interface:
    path: ../video_duration_native_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^10.0.0
